<?php

namespace Database\Seeders;

use App\Models\PemakaianKendaraan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TransaksiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $transaksis = [
            // =====================================AVANZA===============================================
            [
                'id_kendaraan' => 1,
                'bulan' => 1,
                'tahun' => 2023,
                'jumlah_transaksi' => 102,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 2,
                'tahun' => 2023,
                'jumlah_transaksi' => 78,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 3,
                'tahun' => 2023,
                'jumlah_transaksi' => 81,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 4,
                'tahun' => 2023,
                'jumlah_transaksi' => 112,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 5,
                'tahun' => 2023,
                'jumlah_transaksi' => 108,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 6,
                'tahun' => 2023,
                'jumlah_transaksi' => 92,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 7,
                'tahun' => 2023,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 8,
                'tahun' => 2023,
                'jumlah_transaksi' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 9,
                'tahun' => 2023,
                'jumlah_transaksi' => 74,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 10,
                'tahun' => 2023,
                'jumlah_transaksi' => 81,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 11,
                'tahun' => 2023,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 12,
                'tahun' => 2023,
                'jumlah_transaksi' => 99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'jumlah_transaksi' => 102,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 2,
                'tahun' => 2024,
                'jumlah_transaksi' => 79,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 3,
                'tahun' => 2024,
                'jumlah_transaksi' => 83,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 4,
                'tahun' => 2024,
                'jumlah_transaksi' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 5,
                'tahun' => 2024,
                'jumlah_transaksi' => 106,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 6,
                'tahun' => 2024,
                'jumlah_transaksi' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 7,
                'tahun' => 2024,
                'jumlah_transaksi' => 84,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 8,
                'tahun' => 2024,
                'jumlah_transaksi' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 9,
                'tahun' => 2024,
                'jumlah_transaksi' => 72,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 10,
                'tahun' => 2024,
                'jumlah_transaksi' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 11,
                'tahun' => 2024,
                'jumlah_transaksi' => 84,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 12,
                'tahun' => 2024,
                'jumlah_transaksi' => 97,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 1,
                'tahun' => 2025,
                'jumlah_transaksi' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 2,
                'tahun' => 2025,
                'jumlah_transaksi' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 3,
                'tahun' => 2025,
                'jumlah_transaksi' => 84,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // =====================================Xenia===============================================
            [
                'id_kendaraan' => 2,
                'bulan' => 1,
                'tahun' => 2023,
                'jumlah_transaksi' => 108,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 2,
                'tahun' => 2023,
                'jumlah_transaksi' => 81,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 3,
                'tahun' => 2023,
                'jumlah_transaksi' => 86,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 4,
                'tahun' => 2023,
                'jumlah_transaksi' => 119,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 5,
                'tahun' => 2023,
                'jumlah_transaksi' => 117,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 6,
                'tahun' => 2023,
                'jumlah_transaksi' => 97,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 7,
                'tahun' => 2023,
                'jumlah_transaksi' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 8,
                'tahun' => 2023,
                'jumlah_transaksi' => 82,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 9,
                'tahun' => 2023,
                'jumlah_transaksi' => 77,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 10,
                'tahun' => 2023,
                'jumlah_transaksi' => 86,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 11,
                'tahun' => 2023,
                'jumlah_transaksi' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 12,
                'tahun' => 2023,
                'jumlah_transaksi' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'jumlah_transaksi' => 109,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 2,
                'tahun' => 2024,
                'jumlah_transaksi' => 84,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 3,
                'tahun' => 2024,
                'jumlah_transaksi' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 4,
                'tahun' => 2024,
                'jumlah_transaksi' => 117,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 5,
                'tahun' => 2024,
                'jumlah_transaksi' => 115,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 6,
                'tahun' => 2024,
                'jumlah_transaksi' => 97,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 7,
                'tahun' => 2024,
                'jumlah_transaksi' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 8,
                'tahun' => 2024,
                'jumlah_transaksi' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 9,
                'tahun' => 2024,
                'jumlah_transaksi' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 10,
                'tahun' => 2024,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 11,
                'tahun' => 2024,
                'jumlah_transaksi' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 12,
                'tahun' => 2024,
                'jumlah_transaksi' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 1,
                'tahun' => 2025,
                'jumlah_transaksi' => 109,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 2,
                'tahun' => 2025,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 3,
                'tahun' => 2025,
                'jumlah_transaksi' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // =====================================Ertiga===============================================
            [
                'id_kendaraan' => 3,
                'bulan' => 1,
                'tahun' => 2023,
                'jumlah_transaksi' => 96,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 2,
                'tahun' => 2023,
                'jumlah_transaksi' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 3,
                'tahun' => 2023,
                'jumlah_transaksi' => 77,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 4,
                'tahun' => 2023,
                'jumlah_transaksi' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 5,
                'tahun' => 2023,
                'jumlah_transaksi' => 98,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 6,
                'tahun' => 2023,
                'jumlah_transaksi' => 86,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 7,
                'tahun' => 2023,
                'jumlah_transaksi' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 8,
                'tahun' => 2023,
                'jumlah_transaksi' => 72,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 9,
                'tahun' => 2023,
                'jumlah_transaksi' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 10,
                'tahun' => 2023,
                'jumlah_transaksi' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 11,
                'tahun' => 2023,
                'jumlah_transaksi' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 12,
                'tahun' => 2023,
                'jumlah_transaksi' => 92,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'jumlah_transaksi' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 2,
                'tahun' => 2024,
                'jumlah_transaksi' => 76,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 3,
                'tahun' => 2024,
                'jumlah_transaksi' => 79,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 4,
                'tahun' => 2024,
                'jumlah_transaksi' => 103,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 5,
                'tahun' => 2024,
                'jumlah_transaksi' => 97,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 6,
                'tahun' => 2024,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 7,
                'tahun' => 2024,
                'jumlah_transaksi' => 79,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 8,
                'tahun' => 2024,
                'jumlah_transaksi' => 72,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 9,
                'tahun' => 2024,
                'jumlah_transaksi' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 10,
                'tahun' => 2024,
                'jumlah_transaksi' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 11,
                'tahun' => 2024,
                'jumlah_transaksi' => 78,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 12,
                'tahun' => 2024,
                'jumlah_transaksi' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 1,
                'tahun' => 2025,
                'jumlah_transaksi' => 96,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 2,
                'tahun' => 2025,
                'jumlah_transaksi' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 3,
                'tahun' => 2025,
                'jumlah_transaksi' => 81,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================Innova===============================================
            [
                'id_kendaraan' => 4,
                'bulan' => 1,
                'tahun' => 2023,
                'jumlah_transaksi' => 114,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 2,
                'tahun' => 2023,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 3,
                'tahun' => 2023,
                'jumlah_transaksi' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 4,
                'tahun' => 2023,
                'jumlah_transaksi' => 123,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 5,
                'tahun' => 2023,
                'jumlah_transaksi' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 6,
                'tahun' => 2023,
                'jumlah_transaksi' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 7,
                'tahun' => 2023,
                'jumlah_transaksi' => 96,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 8,
                'tahun' => 2023,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 9,
                'tahun' => 2023,
                'jumlah_transaksi' => 81,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 10,
                'tahun' => 2023,
                'jumlah_transaksi' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 11,
                'tahun' => 2023,
                'jumlah_transaksi' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 12,
                'tahun' => 2023,
                'jumlah_transaksi' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 1,
                'tahun' => 2024,
                'jumlah_transaksi' => 114,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 2,
                'tahun' => 2024,
                'jumlah_transaksi' => 87,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 3,
                'tahun' => 2024,
                'jumlah_transaksi' => 92,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 4,
                'tahun' => 2024,
                'jumlah_transaksi' => 122,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 5,
                'tahun' => 2024,
                'jumlah_transaksi' => 118,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 6,
                'tahun' => 2024,
                'jumlah_transaksi' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 7,
                'tahun' => 2024,
                'jumlah_transaksi' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 8,
                'tahun' => 2024,
                'jumlah_transaksi' => 83,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 9,
                'tahun' => 2024,
                'jumlah_transaksi' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 10,
                'tahun' => 2024,
                'jumlah_transaksi' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 11,
                'tahun' => 2024,
                'jumlah_transaksi' => 94,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 12,
                'tahun' => 2024,
                'jumlah_transaksi' => 109,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 1,
                'tahun' => 2025,
                'jumlah_transaksi' => 115,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 2,
                'tahun' => 2025,
                'jumlah_transaksi' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 3,
                'tahun' => 2025,
                'jumlah_transaksi' => 93,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($transaksis as $transaksi) {
            PemakaianKendaraan::create($transaksi);
        }
    }
}
