<?php

namespace Database\Seeders;

use App\Models\PemakaianKendaraan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TransaksiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $transaksis = [
            // =====================================AVANZA===============================================
            [
                'id_kendaraan' => 1,
                'bulan' => 1,
                'tahun' => 2023,
                'jumlah_transaksi' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 2,
                'tahun' => 2023,
                'jumlah_transaksi' => 94,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 3,
                'tahun' => 2023,
                'jumlah_transaksi' => 112,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 4,
                'tahun' => 2023,
                'jumlah_transaksi' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 5,
                'tahun' => 2023,
                'jumlah_transaksi' => 116,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 6,
                'tahun' => 2023,
                'jumlah_transaksi' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 7,
                'tahun' => 2023,
                'jumlah_transaksi' => 145,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 8,
                'tahun' => 2023,
                'jumlah_transaksi' => 101,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 9,
                'tahun' => 2023,
                'jumlah_transaksi' => 115,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 10,
                'tahun' => 2023,
                'jumlah_transaksi' => 115,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 11,
                'tahun' => 2023,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 12,
                'tahun' => 2023,
                'jumlah_transaksi' => 250,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 1,
                'tahun' => 2024,
                'jumlah_transaksi' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 2,
                'tahun' => 2024,
                'jumlah_transaksi' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 3,
                'tahun' => 2024,
                'jumlah_transaksi' => 112,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 4,
                'tahun' => 2024,
                'jumlah_transaksi' => 195,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 5,
                'tahun' => 2024,
                'jumlah_transaksi' => 114,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 6,
                'tahun' => 2024,
                'jumlah_transaksi' => 193,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 7,
                'tahun' => 2024,
                'jumlah_transaksi' => 135,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 8,
                'tahun' => 2024,
                'jumlah_transaksi' => 108,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 9,
                'tahun' => 2024,
                'jumlah_transaksi' => 119,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 10,
                'tahun' => 2024,
                'jumlah_transaksi' => 113,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 11,
                'tahun' => 2024,
                'jumlah_transaksi' => 96,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 12,
                'tahun' => 2024,
                'jumlah_transaksi' => 255,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 1,
                'tahun' => 2025,
                'jumlah_transaksi' => 108,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 2,
                'tahun' => 2025,
                'jumlah_transaksi' => 101,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 1,
                'bulan' => 3,
                'tahun' => 2025,
                'jumlah_transaksi' => 250,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // =====================================Xenia===============================================
            [
                'id_kendaraan' => 2,
                'bulan' => 1,
                'tahun' => 2023,
                'jumlah_transaksi' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 2,
                'tahun' => 2023,
                'jumlah_transaksi' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 3,
                'tahun' => 2023,
                'jumlah_transaksi' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 4,
                'tahun' => 2023,
                'jumlah_transaksi' => 112,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 5,
                'tahun' => 2023,
                'jumlah_transaksi' => 71,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 6,
                'tahun' => 2023,
                'jumlah_transaksi' => 102,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 7,
                'tahun' => 2023,
                'jumlah_transaksi' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 8,
                'tahun' => 2023,
                'jumlah_transaksi' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 9,
                'tahun' => 2023,
                'jumlah_transaksi' => 69,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 10,
                'tahun' => 2023,
                'jumlah_transaksi' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 11,
                'tahun' => 2023,
                'jumlah_transaksi' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 12,
                'tahun' => 2023,
                'jumlah_transaksi' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 1,
                'tahun' => 2024,
                'jumlah_transaksi' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 2,
                'tahun' => 2024,
                'jumlah_transaksi' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 3,
                'tahun' => 2024,
                'jumlah_transaksi' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 4,
                'tahun' => 2024,
                'jumlah_transaksi' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 5,
                'tahun' => 2024,
                'jumlah_transaksi' => 79,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 6,
                'tahun' => 2024,
                'jumlah_transaksi' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 7,
                'tahun' => 2024,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 8,
                'tahun' => 2024,
                'jumlah_transaksi' => 92,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 9,
                'tahun' => 2024,
                'jumlah_transaksi' => 66,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 10,
                'tahun' => 2024,
                'jumlah_transaksi' => 98,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 11,
                'tahun' => 2024,
                'jumlah_transaksi' => 65,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 12,
                'tahun' => 2024,
                'jumlah_transaksi' => 145,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 1,
                'tahun' => 2025,
                'jumlah_transaksi' => 82,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 2,
                'tahun' => 2025,
                'jumlah_transaksi' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 2,
                'bulan' => 3,
                'tahun' => 2025,
                'jumlah_transaksi' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // =====================================Ertiga===============================================
            [
                'id_kendaraan' => 3,
                'bulan' => 1,
                'tahun' => 2023,
                'jumlah_transaksi' => 63,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 2,
                'tahun' => 2023,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 3,
                'tahun' => 2023,
                'jumlah_transaksi' => 111,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 4,
                'tahun' => 2023,
                'jumlah_transaksi' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 5,
                'tahun' => 2023,
                'jumlah_transaksi' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 6,
                'tahun' => 2023,
                'jumlah_transaksi' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 7,
                'tahun' => 2023,
                'jumlah_transaksi' => 122,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 8,
                'tahun' => 2023,
                'jumlah_transaksi' => 115,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 9,
                'tahun' => 2023,
                'jumlah_transaksi' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 10,
                'tahun' => 2023,
                'jumlah_transaksi' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 11,
                'tahun' => 2023,
                'jumlah_transaksi' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 12,
                'tahun' => 2023,
                'jumlah_transaksi' => 195,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 1,
                'tahun' => 2024,
                'jumlah_transaksi' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 2,
                'tahun' => 2024,
                'jumlah_transaksi' => 88,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 3,
                'tahun' => 2024,
                'jumlah_transaksi' => 109,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 4,
                'tahun' => 2024,
                'jumlah_transaksi' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 5,
                'tahun' => 2024,
                'jumlah_transaksi' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 6,
                'tahun' => 2024,
                'jumlah_transaksi' => 165,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 7,
                'tahun' => 2024,
                'jumlah_transaksi' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 8,
                'tahun' => 2024,
                'jumlah_transaksi' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 9,
                'tahun' => 2024,
                'jumlah_transaksi' => 104,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 10,
                'tahun' => 2024,
                'jumlah_transaksi' => 91,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 11,
                'tahun' => 2024,
                'jumlah_transaksi' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 12,
                'tahun' => 2024,
                'jumlah_transaksi' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 1,
                'tahun' => 2025,
                'jumlah_transaksi' => 74,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 2,
                'tahun' => 2025,
                'jumlah_transaksi' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 3,
                'bulan' => 3,
                'tahun' => 2025,
                'jumlah_transaksi' => 107,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =====================================Innova===============================================
            [
                'id_kendaraan' => 4,
                'bulan' => 1,
                'tahun' => 2023,
                'jumlah_transaksi' => 101,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 2,
                'tahun' => 2023,
                'jumlah_transaksi' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 3,
                'tahun' => 2023,
                'jumlah_transaksi' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 4,
                'tahun' => 2023,
                'jumlah_transaksi' => 225,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 5,
                'tahun' => 2023,
                'jumlah_transaksi' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 6,
                'tahun' => 2023,
                'jumlah_transaksi' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 7,
                'tahun' => 2023,
                'jumlah_transaksi' => 175,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 8,
                'tahun' => 2023,
                'jumlah_transaksi' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 9,
                'tahun' => 2023,
                'jumlah_transaksi' => 101,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 10,
                'tahun' => 2023,
                'jumlah_transaksi' => 155,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 11,
                'tahun' => 2023,
                'jumlah_transaksi' => 98,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 12,
                'tahun' => 2023,
                'jumlah_transaksi' => 230,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 1,
                'tahun' => 2024,
                'jumlah_transaksi' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 2,
                'tahun' => 2024,
                'jumlah_transaksi' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 3,
                'tahun' => 2024,
                'jumlah_transaksi' => 185,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 4,
                'tahun' => 2024,
                'jumlah_transaksi' => 199,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 5,
                'tahun' => 2024,
                'jumlah_transaksi' => 170,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 6,
                'tahun' => 2024,
                'jumlah_transaksi' => 196,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 7,
                'tahun' => 2024,
                'jumlah_transaksi' => 177,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 8,
                'tahun' => 2024,
                'jumlah_transaksi' => 188,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 9,
                'tahun' => 2024,
                'jumlah_transaksi' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 10,
                'tahun' => 2024,
                'jumlah_transaksi' => 144,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 11,
                'tahun' => 2024,
                'jumlah_transaksi' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 12,
                'tahun' => 2024,
                'jumlah_transaksi' => 220,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 1,
                'tahun' => 2025,
                'jumlah_transaksi' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 2,
                'tahun' => 2025,
                'jumlah_transaksi' => 190,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_kendaraan' => 4,
                'bulan' => 3,
                'tahun' => 2025,
                'jumlah_transaksi' => 265,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($transaksis as $transaksi) {
            PemakaianKendaraan::create($transaksi);
        }
    }
}
